### ISSUE TITLE
Suggest returns a response but it's not reflected in the view.

### ISSUE THREAD

**Issue by elboletaire** [cakephp/plugins.cakephp.org#84]
Suggesting a plugin only removes the suggested url from the input. 

Checking the "network" tab we can see that the response is returned by the server but the view does not reflect it.

**Comment by ADmad** [comment]
Yup a visual indication to convey to the user that his request is successful is missing.

**Comment by elboletaire** [comment]
I remember that indication, can it be? Or I've dreamed with it?

**Comment by ADmad** [comment]
I don't know :)  Maybe @josegonzalez does.

**Comment by josegonzalez** [comment]
Hmm, that used to work. I'll take a look.

**Comment by burzum** [comment]
@josegonzalez this is still an issue, I just came across it myself.

**Comment by josegonzalez** [comment]
Done in latest version.

**Comment by elboletaire** [comment]
After the upgrade most of my packages disappeared from the plugins directory... have you removed things? Or is it a bug?

**Comment by josegonzalez** [comment]
I don't know how many you had online, but I don't see that many on your profile. I believe I may have removed anything 1.x or anything without composer. This is all being tweaked over the next few days/weeks though as I work through categorization issues, so you may see things pop back up.

**Comment by elboletaire** [comment]
If you search for "elboletaire" none of my cake 3.x plugins are shown, where, at least, these should be shown:

- https://github.com/elboletaire/twbs-cake-plugin
- https://github.com/elboletaire/less-cake-plugin
- https://github.com/elboletaire/docs-cake-plugin

But I only can see this one: 

- https://github.com/elboletaire/piwik-cakephp-plugin

![imatge](https://user-images.githubusercontent.com/153305/35104891-83d29528-fc6a-11e7-8d80-45a70123a297.png)

**Comment by josegonzalez** [comment]
Yep, as I said, i am working on the categorization issues and will have those sorted by the end of the week. Thanks for being patient.

**Comment by elboletaire** [comment]
Ok thanks @josegonzalez! That's why I was asking here and not directly opening a new issue 😉
