### ISSUE TITLE
"suggest plugin" does not answer

### ISSUE THREAD

**Issue by ava007** [cakephp/plugins.cakephp.org#86]
On http://plugins.cakephp.org/ I've tried to suggest a new package:

a) Entering "https://github.com/ava007/wnk_translation" in the input field
b) Pressing Button "Suggest"

Response: None, only the input field is cleared instantly.

I'm using Firefox (latest version) on Linux. The same happens in the Chrome browser.

Expected behavior: giving a response "successfully added....".

**Comment by josegonzalez** [comment]
Done in latest version :)
